title: Believe it
subtitle: 相信不屈不挠的努力,相信战胜死亡的年轻
description: O ever youthful, O ever weeping
keywords: null
author: fightinggg
language: zh-CN
timezone: Asia/Shanghai
url: https://fightinggg.github.io
permalink: ':abbrlink.html'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: ./
i18n_dir: ':lang'
skip_render:
  - readme.md
  - _posts2/**
  - _posts3/**
  - .github/**/*
  - '**/*.html'
  - ACM/**
  - '**/*.json'
  - '**/*.js'
  - '**/*.css'
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: false
  exclude_languages:
    - mermaid
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
index_generator:
  path: ''
  per_page: 10
  order_by: '-updated'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: false
per_page: 30
pagination_dir: page
include:
  - .github/**/*
exclude:
  - '**/*.ignore_deploy'
ignore:
  - hexo-generator-baidu-sitemap
  - hexo-generator-sitemap
theme: next
deploy:
  - type: git
    ignore_hidden: false
    repo:
      github: git@github.com:fightinggg/fightinggg.github.io.git
    branch: master
root: /
multiThemeRoot: /
multiTheme: >-
  next,hexonext,butterfly,volantis,yearn,yilia,shoka,indigo,apollo,landscape,cactus,matery,icarus,fluid,material
a: a
baidusitemap:
  path: baidusitemap.xml
sitemap:
  path: sitemap.xml
  template: gitalk/sitemap_template.xml
  rel: false
  tag: true
  category: false
baidu_url_submit:
  count: 10000
  host: http://fightinggg.top
  token: e2sgSK99VXdpyZgS
  path: baidu_urls.txt
encrypt:
  enable: true
  abstract: 有东西被加密了, 请输入密码查看.
  message: 您好, 这里需要密码
  wrong_pass_message: 抱歉, 这个密码看着不太对, 请再试试.
  wrong_hash_message: 抱歉, 这个文章不能被校验, 不过您还是能看看解密后的内容.
search:
  path: search.xml
  field: post
  format: html
  limit: 10000
tags: >-
  C++, Boost, STL, \ Java, Spring, SpringBoot, SpringMVC, SpringCloud, Maven,
  JVM, MyBatis, JPA \ Python, 爬虫, \ 大数据, 并发, 集群, 分布式,Hadoop,Zookeeper,Kafka, \
  SQL, 数据库, redis, \ codeforces, hdu, bzoj, uoj,牛客, \ 数据结构,线段树,主席树, 平衡树, 字典树,
  前缀树,tree,heap,trie, \ 算法, hash, 二分, 倍增, \ 数学, \ 字符串, 自动机, \ dp, euler,
  datastructure,dsu, \ 图论, 最短路, 最小生成树, 生成树, 最大团, 最大独立集, \ 字符串, KMP, Manacher,
  后缀数组, 字符串Hash, 后缀自动机, 回文树, \ 位运算, xor, \ 区间, 区间问题, \ 线性基, \ 计算几何, \ Stern,
  Brocot, \ linux, git, \ vim, \ hexo, kernel, LDA, kernel, \ functions, k子段和,
  k短路, lct,  lis, machine, \ learning, math, mathematics, matrix, metric_space,
  min25筛, myself_library, mysql, \ pollard, rho, supervised, learning, \
  两分数间分母最小的分数, 中国剩余定理, 二分图匹配, 二次剩余, \ 凸壳, 分数二分, 前缀线性基, 后缀自动机, 启发式查询, \ 图连通性,
  序列自动机, 操作系统, 支配树, \ 数据结构, 数论, 斐波那契, 斜率, 最大流最小割, 最小字典序, 最小表示法, 最短路, 有向图判环, \
  期望, 期望复杂度, 杜教筛, 构造, 树链剖分, 欧几里得算法, \ 珂朵莉树, 生成树, 积性函数, 笛卡尔树, 等比数列, 算法复杂度分析, \
  类欧几里得算法, 素数,  虚树, 计算机网络, 记忆化, \ 设计模式, 费用流, 软件测试, 软件需求, 霍尔定理, \ 实习, 腾讯, 阿里, 字节,
  网易, 美团
linkable:
  - key: PING
    url: /QQPNNQ.html#PING
  - key: ICMP
    url: /QQTKJ0.html#ICMP
  - key: 进程
    url: /QPI740.html#第4章-进程
  - key: 地址转换
    url: /QPI740.html#第15章-机制：地址转换
  - key: 分页
    url: /QPI740.html#第18章-分页：介绍
  - key: 锁
    url: /QPI740.html#第28章-锁
  - key: 条件变量
    url: /QPI740.html#第30章-条件变量
  - key: 信号量
    url: /QPI740.html#第31章-信号量
  - key: 文件系统
    url: /QPI740.html#第40章-文件系统实现
  - key: 管道
    url: /QQPI8C.html#管道
  - key: 共享内存
    url: /QQPI8C.html#共享内存
  - key: 变长整型
    url: /QQRP8M.html#变长整型
  - key: zigzag
    url: /QQRP8M.html#zigzag
symbols_count_time:
  total_time: false
